### ISSUE TITLE
Target unique user

### ISSUE THREAD

**Issue by antonioberetini** [mfbhatt/capacitor-azure-push-notification#2]
Silly question, how do you target a unique user based on user identifier?

**Comment by mfbhatt** [comment]
You can use the devicetag property to uniquely send the notification to device or group of devices based on the tag value.

AzurePushNotifications.requestPermissions().then((result) => {
      AzurePushNotifications.register({
        notificationHubName: '<AZURE NOTIFICATION HUB NAME>',
        connectionString:
          '<AZURE NOTIFICATION CONNECTION STRING>',
        **deviceTag: '<DEVICE TAG>',**
      }).then(() => {
        AzurePushNotifications.addListener(
          'registration',
          (token: PushNotificationToken) => {
            alert('Push registration success, token: ' + token.value);
          }
        );
      });
    });
