### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Nathan187** [mfbhatt/capacitor-azure-push-notification#4]
doesn't work.  

the contents of the readme file are wrong.  that's the wrong install command.  trying to use that install command...you get a 404.
npm install @mfbhatt/azure-push-notifications seem to work but doesn't build properly in xcode

please proofread your readme file.  and make sure the plugin does indeed work

<img width="1095" alt="Screen Shot 2022-01-07 at 12 42 05 PM" src="https://user-images.githubusercontent.com/1022238/148591808-11c19d58-73ac-4c32-8f2b-e4faceff1f0f.png">

**Comment by jindrichkuba** [comment]
is working fine, inside CapacitorAzurePushNotifications.podspec we have to use s.static_framework = true

**Comment by Nathan187** [comment]
thank you for responding.  i will close now
