### ISSUE TITLE
Release new npm package

### ISSUE THREAD

**Issue by jindrichkuba** [mfbhatt/capacitor-azure-push-notification#6]
Could you please release new npm version, thanks, great plugin btw

**Comment by mfbhatt** [comment]
I have published it

**Comment by jindrichkuba** [comment]
thanks, great work

**Comment by jindrichkuba** [comment]
I dont see there changes, I see it was published 1.0.4

**Comment by jindrichkuba** [comment]
Could you please release version 1.0.9 with fix what I pushed?

thanks, seems version 1.04 doesnt work

**Comment by mfbhatt** [comment]
> 

have you pushed any new changes? I can't see any new changes.

**Comment by jindrichkuba** [comment]
here inside NPM is version 1.04, can you add there version 1.0.9? with latest code from here please https://www.npmjs.com/package/@mfbhatt/azure-push-notifications

**Comment by mfbhatt** [comment]
> here inside NPM is version 1.04, can you add there version 1.0.9? with latest code from here please https://www.npmjs.com/package/@mfbhatt/azure-push-notifications
published version 1.0.10

**Comment by jindrichkuba** [comment]
thanks a lot, I appreciated
