### ISSUE TITLE
No podspec found for `MfbhattAzurePushNotifications` 

### ISSUE THREAD

**Issue by jindrichkuba** [mfbhatt/capacitor-azure-push-notification#7]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/10973848/187419857-27f6c8ac-385d-48ca-aaf7-9266fca129e5.png">

**Comment by jindrichkuba** [comment]
version 1.0.10 doesnt work, is working version 1.09 with   s.static_framework = true inside file CapacitorAzurePushNotifications.podspec

**Comment by mfbhatt** [comment]
> version 1.0.10 doesnt work, is working version 1.09 with s.static_framework = true inside file CapacitorAzurePushNotifications.podspec

There is no change in CapacitorAzurePushNotifications.podspec and s.static_framework = true is set in latest version

**Comment by jindrichkuba** [comment]
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/10973848/187422436-b0edcaaf-9b21-4def-81f3-02849bfaeef5.png">

**Comment by mfbhatt** [comment]
> <img alt="image" width="1469" src="https://user-images.githubusercontent.com/10973848/187422436-b0edcaaf-9b21-4def-81f3-02849bfaeef5.png">

same code i have published

**Comment by jindrichkuba** [comment]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/10973848/187425056-7d9d5e38-c054-4a53-bf99-08148b3050a7.png">
with new version this file is missing

**Comment by jindrichkuba** [comment]
version 1.10.
<img width="383" alt="image" src="https://user-images.githubusercontent.com/10973848/187425225-e8f7ec2d-6a18-4e0d-86e0-b41c7991407e.png">

**Comment by devjkuba** [comment]
inside version 10 missing file CapacitorAzurePushNotifications.podspec

**Comment by mfbhatt** [comment]
> inside version 10 missing file CapacitorAzurePushNotifications.podspec

I have fixed the issue

**Comment by mfbhatt** [comment]
I have pushed version 11. It is fixed now.

**Comment by devjkuba** [comment]
https://www.npmjs.com/package/@mfbhatt/azure-push-notifications I see version 10, can you please publish

**Comment by mfbhatt** [comment]
it is published

> https://www.npmjs.com/package/@mfbhatt/azure-push-notifications I see version 10, can you please publish

it is published

**Comment by jindrichkuba** [comment]
] Analyzing dependencies
        [!] No podspec found for `MfbhattAzurePushNotifications` in
        `../../node_modules/@mfbhatt/azure-push-notifications`

**Comment by mfbhatt** [comment]
> 

can you uninstall the plugin and then try to install. I installed the latest version and the .podspec file is present

**Comment by jindrichkuba** [comment]
I did, same issue Analyzing dependencies
[!] No podspec found for MfbhattAzurePushNotifications in
../../node_modules/@mfbhatt/azure-push-notifications

**Comment by mfbhatt** [comment]
> I did, same issue Analyzing dependencies [!] No podspec found for MfbhattAzurePushNotifications in ../../node_modules/@mfbhatt/azure-push-notifications

run the below command first and then try to install
npm uninstall @mfbhatt/azure-push-notifications
