### ISSUE TITLE
Does not seem to register the device to the hub

### ISSUE THREAD

**Issue by ken2k** [mfbhatt/capacitor-azure-push-notification#8]
Hi,
First of all, thanks for the plugin.

I'm trying to make it work, with no luck for now. I followed the instructions, successfully got a token ("alert: Push registration success, token: tzxOW...."), but cannot receive notifications. When sending a test notification through the Azure Portal, it always returns "Message was successfully sent, but there were no matching targets.".

There is indeed no registered device despite the successful token reception by the phone, as the backend .NET API (NotificationHubClient.GetAllRegistrationsAsync) returns 0 registrations.

Any idea why this would fail? I assume the configuration of the plugin is valid (connection string - tested both at the Notification Hub and the Notification Hub Namespace levels, hub name, google-services.json file... etc.) because it returns a valid token. I'm running out of ideas. Thanks.

**Comment by mfbhatt** [comment]
> Hi, First of all, thanks for the plugin.
> 
> I'm trying to make it work, with no luck for now. I followed the instructions, successfully got a token ("alert: Push registration success, token: tzxOW...."), but cannot receive notifications. When sending a test notification through the Azure Portal, it always returns "Message was successfully sent, but there were no matching targets.".
> 
> There is indeed no registered device despite the successful token reception by the phone, as the backend .NET API (NotificationHubClient.GetAllRegistrationsAsync) returns 0 registrations.
> 
> Any idea why this would fail? I assume the configuration of the plugin is valid (connection string - tested both at the Notification Hub and the Notification Hub Namespace levels, hub name, google-services.json file... etc.) because it returns a valid token. I'm running out of ideas. Thanks.

are you adding any devices tags when you register the device and also when you send the notification are you adding any tags there. if yes, both the tags should match.

**Comment by ken2k** [comment]
Hi,

Thanks a lot for helping figuring out what the issue is.

I've tried with both no tag at all, or with a fixed value ('12'). Same problem with both. Here is the relevant Angular code I'm using on the ionic app. This is called upon app component initialization. I've commented with some explanations, but it really only is your example:

```
import { Injectable } from '@angular/core';
import { Platform } from '@ionic/angular';
import { ActionPerformed, AzurePushNotifications, AzurePushNotificationSchema, Token } from '@mfbhatt/azure-push-notifications'; 
import { LoggerService } from './logger.service';

...

    // Called only on Android devices (for now), upon app component init
    public async initAzureNotificationHubPluginAsync() {
        AzurePushNotifications.requestPermissions().then((result) => {
          AzurePushNotifications.register({
            notificationHubName: 'testhub',    // Name of my hub
            connectionString: 'Endpoint=sb://xxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=yyyy',    // Connection string with all rights on the Notification Hub namespace, also tried with a connectionString to the hub itself
            deviceTag: '12',  // Either empty or a value (tried with both on the test notification on Azure Portal)
          }).then(() => {
            AzurePushNotifications.addListener(
              'registration',
              (token: Token) => {
                // This successfully returns a value, I assume this means the registration should be OK
                alert('Azure: Push registration success, token: ' + token.value);
              }
            );
          });
        });


        AzurePushNotifications.addListener(
          'registrationError',
          (error: any) => {
            // Does not trigger at all (would be the nominal case)
            alert('Azure: Error on registration: ' + JSON.stringify(error));
          }
        );

        AzurePushNotifications.addListener(
          'pushNotificationReceived',
          (notification: AzurePushNotificationSchema) => {
            // Never called
            alert('Azure: Push received: ' + JSON.stringify(notification));
          }
        );
        AzurePushNotifications.addListener(
          'pushNotificationActionPerformed',
          (notification: ActionPerformed) => {
            // Never called
            alert('Azure: Push action performed: ' + JSON.stringify(notification));
          }
        );
      }
    }
```

As for the Azure Notifications Hub configuration, I have copied/pasted the Firebase API key from here:

![image](https://user-images.githubusercontent.com/65537282/189900592-e0a5bf87-0abb-454a-8043-980d1797613d.png)

Used in the Azure Portal here:

![image](https://user-images.githubusercontent.com/65537282/189900656-70641dc8-6316-4645-ba94-700c5f032df3.png)

And the result from the test notification:

![image](https://user-images.githubusercontent.com/65537282/189900800-9de7729d-7c3d-4669-bf7d-4f2cf2d3a0db.png)

**Comment by mfbhatt** [comment]
> deviceTag

can you keep the application in background and send the push notification from hub

**Comment by ken2k** [comment]
I was aware this could be an issue (https://stackoverflow.com/a/39449228/870604), but I've tried putting the app in background and this does not work either.

Do note I added local notifications to the app instead of the "alert" method call, to make sure I don't miss the reception of an event from the cloud while running on background. The token success still pops-up, but no notification event:

![image](https://user-images.githubusercontent.com/65537282/189912577-a35f4acf-25a2-4a93-9cca-67211b364128.png)

**Comment by mfbhatt** [comment]
> I was aware this could be an issue (https://stackoverflow.com/a/39449228/870604), but I've tried putting the app in background and this does not work either.
> 
> Do note I added local notifications to the app instead of the "alert" method call, to make sure I don't miss the reception of an event from the cloud while running on background. The token success still pops-up, but no notification event:
> 
> ![image](https://user-images.githubusercontent.com/65537282/189912577-a35f4acf-25a2-4a93-9cca-67211b364128.png)

are you testing it on simulator or mobile device. I would suggest to use mobile device.

**Comment by ken2k** [comment]
Thanks, but this is already an actual physical mobile device (Xiaomi Redmi Note 8 Pro), the application is deployed on my phone through Android Studio.

**Comment by ken2k** [comment]
I think there is something wrong with how the Azure API is called by the plugin. I dug into the log traces and found the following error message when trying to register:



```
E/Volley: [45673] NetworkUtility.shouldRetryException: Unexpected response code 400 for https://xxxxxx.servicebus.windows.net/testhub/installations/563be277-d019-40c5-9178-1121645ff31f?api-version=2020-06
E/ANH: unable to save installation: com.microsoft.windowsazure.messaging.notificationhubs.ClientException: Azure Notification Hub request failed with status 400: <Error><Code>400</Code><Detail>Installation validation failed with following error(s):&#xD;
    An invalid tag(s) ',12' was supplied. Valid tag characters are alphanumeric, _, @, -, ., : and #..TrackingId:4a47c894-9c0b-4d69-ae3f-9d9bde0d6b3e_G1,TimeStamp:9/13/2022 2:16:53 PM</Detail></Error>
```

Do note the value in the error message is `',12'`, but I provided `'12'` (without the ','). Also do note now I get the following error when trying again with the same request:

```
E/Volley: [45754] NetworkUtility.shouldRetryException: Unexpected response code 400 for https://xxxxxx.servicebus.windows.net/testhub/installations/563be277-d019-40c5-9178-1121645ff31f?api-version=2020-06
E/ANH: unable to save installation: com.microsoft.windowsazure.messaging.notificationhubs.ClientException: Azure Notification Hub request failed with status 400: <Error><Code>400</Code><Detail>array contains a Json token other than a string.TrackingId:52c6b591-e60e-437d-9cf3-7bcf11092ba5_G0,TimeStamp:9/13/2022 2:36:08 PM</Detail></Error>
```

Any idea @mfbhatt ? Thanks.

**Comment by mfbhatt** [comment]
> I think there is something wrong with how the Azure API is called by the plugin. I dug into the log traces and found the following error message when trying to register:
> 
> ```
> E/Volley: [45673] NetworkUtility.shouldRetryException: Unexpected response code 400 for https://xxxxxx.servicebus.windows.net/testhub/installations/563be277-d019-40c5-9178-1121645ff31f?api-version=2020-06
> E/ANH: unable to save installation: com.microsoft.windowsazure.messaging.notificationhubs.ClientException: Azure Notification Hub request failed with status 400: <Error><Code>400</Code><Detail>Installation validation failed with following error(s):&#xD;
>     An invalid tag(s) ',12' was supplied. Valid tag characters are alphanumeric, _, @, -, ., : and #..TrackingId:4a47c894-9c0b-4d69-ae3f-9d9bde0d6b3e_G1,TimeStamp:9/13/2022 2:16:53 PM</Detail></Error>
> ```
> 
> Do note the value in the error message is `',12'`, but I provided `'12'` (without the ','). Also do note now I get the following error when trying again with the same request:
> 
> ```
> E/Volley: [45754] NetworkUtility.shouldRetryException: Unexpected response code 400 for https://xxxxxx.servicebus.windows.net/testhub/installations/563be277-d019-40c5-9178-1121645ff31f?api-version=2020-06
> E/ANH: unable to save installation: com.microsoft.windowsazure.messaging.notificationhubs.ClientException: Azure Notification Hub request failed with status 400: <Error><Code>400</Code><Detail>array contains a Json token other than a string.TrackingId:52c6b591-e60e-437d-9cf3-7bcf11092ba5_G0,TimeStamp:9/13/2022 2:36:08 PM</Detail></Error>
> ```
> 
> Any idea @mfbhatt ? Thanks.

instead of '12' for tags can you use some alpha values like 'demo'

**Comment by ken2k** [comment]
I tried, but I got the same result. Here is the relevant code:

```
const deviceTag = 'demo';
    this.logger.log('PushNotificationsService', 'Using deviceTag: ' + deviceTag);
    AzurePushNotifications.requestPermissions().then((result) => {
      AzurePushNotifications.register({
        notificationHubName: 'testhub',
        connectionString: 'Endpoint=sb://xxx.servicebus.windows.net/;SharedAccessKeyName=listen;SharedAccessKey=yyy',
        deviceTag
      }).then(() => {
        AzurePushNotifications.addListener(
          'registration',
          (token: Token) => {
            this.localNotificationsService.pushNotification({
              title: 'Push registration success',
              message: token.value,
              channelId: LocalNotificationsService.pushNotificationsChannelId });
            alert('Azure: Push registration success, token: ' + token.value);
            this.logger.log('PushNotificationsService', 'Token: ' + token.value);
          }
        );
      });
    });
```

Full log with error:


**I/Capacitor/Console: File: http://localhost/main.js - Line 1 - Msg: #PushNotificationsService - 13/09/2022 17:21:22 -- Using deviceTag: demo**
**V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 7987603, pluginId: AzurePushNotifications, methodName: addListener
V/Capacitor: callback: 7987603, pluginId: AzurePushNotifications, methodName: addListener, methodData: {"eventName":"registrationError"}
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 7987604, pluginId: AzurePushNotifications, methodName: addListener
V/Capacitor: callback: 7987604, pluginId: AzurePushNotifications, methodName: addListener, methodData: {"eventName":"pushNotificationReceived"}
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 7987605, pluginId: AzurePushNotifications, methodName: addListener
V/Capacitor: callback: 7987605, pluginId: AzurePushNotifications, methodName: addListener, methodData: {"eventName":"pushNotificationActionPerformed"}**
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 7987606, pluginId: SecureStoragePlugin, methodName: get
V/Capacitor: callback: 7987606, pluginId: SecureStoragePlugin, methodName: get, methodData: {"key":"token_response"}
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 7987607, pluginId: App, methodName: addListener
V/Capacitor: callback: 7987607, pluginId: App, methodName: addListener, methodData: {"eventName":"appUrlOpen"}
V/Capacitor/Plugin: To native (Cordova plugin): callbackId: BackgroundMode905637872, service: BackgroundMode, action: enable, actionArgs: []
V/Capacitor/Plugin: To native (Cordova plugin): callbackId: INVALID, service: BackgroundModeExt, action: battery, actionArgs: []
**V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 7987608, pluginId: AzurePushNotifications, methodName: register
V/Capacitor: callback: 7987608, pluginId: AzurePushNotifications, methodName: register, methodData: {"notificationHubName":"testhub","connectionString":"Endpoint=sb:\/\/xxx.servicebus.windows.net\/;SharedAccessKeyName=listen;SharedAccessKey=yyy","deviceTag":"demo"}**
D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_index-595c1526_js.js
D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_status-tap-130b103e_js.js
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 7987609, pluginId: App, methodName: addListener
V/Capacitor: callback: 7987609, pluginId: App, methodName: addListener, methodData: {"eventName":"backButton"}
D/ANH: Network 553 is available.
D/ANH: Network has been connected.
**V/Capacitor/PushNotificationsPlugin: Notifying listeners for event registration
D/Capacitor/PushNotificationsPlugin: No listeners found for event registration**
...
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/Capacitor/Console: File: http://localhost/ - Line 201 - Msg: undefined
**V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 7987610, pluginId: AzurePushNotifications, methodName: addListener
V/Capacitor: callback: 7987610, pluginId: AzurePushNotifications, methodName: addListener, methodData: {"eventName":"registration"}
V/Capacitor/PushNotificationsPlugin: Notifying listeners for event registration**
**I/Capacitor/Console: File: http://localhost/main.js - Line 1 - Msg: #LocalNotificationsService - 13/09/2022 17:21:24 -- #NOTIF - displaying notification: title=[Push registration success],message=[fzxOWzF3RuSjFE7Kur3rSl:APA91bGHj-zzzz...]**
D/ViewRootImpl[MainActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
E/GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
D/Surface: Surface::connect(this=0x77bd397000,api=1)
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface: Surface::setBufferCount(this=0x77bd397000,bufferCount=3)
D/Surface: Surface::allocateBuffers(this=0x77bd397000)
I/System.out: [okhttp]:check permission begin!
W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out: [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out: [socket]:check permission begin!
W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out: [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out: [OkHttp] sendRequest>>
I/System.out: [OkHttp] sendRequest<<
**E/Volley: [46088] NetworkUtility.shouldRetryException: Unexpected response code 400 for https://xxx.servicebus.windows.net/testhub/installations/563be277-d019-40c5-9178-1121645ff31f?api-version=2020-06
E/ANH: unable to save installation: com.microsoft.windowsazure.messaging.notificationhubs.ClientException: Azure Notification Hub request failed with status 400: <Error><Code>400</Code><Detail>array contains a Json token other than a string.TrackingId:4c1860d7-2641-4d99-bc46-f634d6fd41d5_G5,TimeStamp:9/13/2022 3:21:26 PM</Detail></Error>**

**Comment by ken2k** [comment]
Hi,

Just to let you know that the plugin still does not work for me, and I have found a better alternative anyway. The base idea of your plugin was to directly call the Notifications Hub endpoint from the mobile phone, which would require the connectionString to be known by the device (as shown in the example).

Why this would work (if the Hub endpoint did not fail with a 400), this is probably not the recommended way to do it, as there are associated security issues to let the device use the connectionString.

What is shown in the MSDN example is that the backend should be responsible to connect to the Notifications Hub, i.e.:

1. on the phone, generate a token through @capacitor/push-notifications
2. on the phone, listen for the pushNotificationReceived event
3. call your backend API with the token as a parameter, in a secured manner (i.e. using an authenticated TLS HTTP call)
4. the backend connects to the Notifications Hub and generates a registration using the client Notifications Hub SDK (.NET in my case) for the specified token / user ID
==> it works just fine for me


Thanks for the help anyway, but you might want to consider the alternative approach.

**Comment by mfbhatt** [comment]
> Hi,
> 
> Just to let you know that the plugin still does not work for me, and I have found a better alternative anyway. The base idea of your plugin was to directly call the Notifications Hub endpoint from the mobile phone, which would require the connectionString to be known by the device (as shown in the example).
> 
> Why this would work (if the Hub endpoint did not fail with a 400), this is probably not the recommended way to do it, as there are associated security issues to let the device use the connectionString.
> 
> What is shown in the MSDN example is that the backend should be responsible to connect to the Notifications Hub, i.e.:
> 
> 1. on the phone, generate a token through @capacitor/push-notifications
> 2. on the phone, listen for the pushNotificationReceived event
> 3. call your backend API with the token as a parameter, in a secured manner (i.e. using an authenticated TLS HTTP call)
> 4. the backend connects to the Notifications Hub and generates a registration using the client Notifications Hub SDK (.NET in my case) for the specified token / user ID
>    ==> it works just fine for me
> 
> Thanks for the help anyway, but you might want to consider the alternative approach.

There seems to be an issue in adding the tags to the notification hub. I have applied the fixed and published new build. if you are interested you can use that.
